# Generated by Django 5.2.17 on 2026-09-14 20:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("operation_key", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("task_name", models.CharField(db_index=True, max_length=120)),
                ("payload", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("leased", "leased"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                            ("dead", "dead"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=6)),
                (
                    "lease_expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_safe_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Operator-safe error context; never manuscript text or secrets.",
                    ),
                ),
                (
                    "submission_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "actor_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="system | reviewer | researcher | webhook",
                        max_length=120,
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=80)),
                (
                    "submission_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("revision_number", models.IntegerField(blank=True, null=True)),
                (
                    "previous_state",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("new_state", models.CharField(blank=True, default="", max_length=40)),
                (
                    "operation_key",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "correlation",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scoped_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "id"],
            },
        ),
    ]
