# Generated by Django 5.2.17 on 2026-09-14 20:53

import accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_id",
                    models.CharField(
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^AUTH-[0-9]{4}$", "AuthorID must look like AUTH-0001"
                            )
                        ],
                    ),
                ),
                (
                    "evidence",
                    models.TextField(
                        help_text="What the claimant offers as evidence of control (public-safe summary)."
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("requested", "requested"),
                            ("verified", "verified"),
                            ("denied", "denied"),
                        ],
                        default="requested",
                        max_length=12,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "condition",
                    models.CharField(
                        help_text="Documented review trigger that authorized this assignment",
                        max_length=120,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("display_name", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("researcher", "Researcher"),
                            ("reviewer", "Reviewer"),
                            ("administrator", "Administrator"),
                        ],
                        default="researcher",
                        max_length=20,
                    ),
                ),
                (
                    "orcid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional scholarly identity metadata. A typed ORCID is not proof of control.",
                        max_length=19,
                    ),
                ),
                (
                    "publish_email",
                    models.BooleanField(
                        default=False,
                        help_text="Email stays private unless the owner opts in.",
                    ),
                ),
                ("terms_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
            managers=[
                ("objects", accounts.models.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuthorBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_id",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^AUTH-[0-9]{4}$", "AuthorID must look like AUTH-0001"
                            )
                        ],
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("reserved", "reserved"),
                            ("registered", "registered"),
                            ("linked", "linked"),
                            ("claim_requested", "claim_requested"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "operation_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Public-safe key of the registration operation",
                        unique=True,
                    ),
                ),
                (
                    "evidence",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="How the binding was established (public-safe).",
                    ),
                ),
                ("linked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="author_binding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
