# Generated by Django 5.2.17 on 2026-09-14 20:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        default="submission",
                        help_text="submission | source_suggestion | relation_proposal | general",
                        max_length=30,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "source_pointer",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("resolution_evidence", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="submissions.question",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Working title shown in the workspace",
                        max_length=300,
                    ),
                ),
                (
                    "intended_object_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Existing SR-OBJ to revise, or blank for a new object family",
                        max_length=13,
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="DOI, archive reference, or source URL supplied instead of / alongside uploads",
                        max_length=500,
                    ),
                ),
                (
                    "draft",
                    models.JSONField(
                        default=dict,
                        help_text="Editable candidate research-object record",
                    ),
                ),
                (
                    "proposed_sources",
                    models.JSONField(
                        default=dict, help_text="{placeholder or SRC id: source record}"
                    ),
                ),
                (
                    "proposed_relations",
                    models.JSONField(
                        default=dict,
                        help_text="{placeholder or REL id: relation record + evidence}",
                    ),
                ),
                (
                    "draft_version",
                    models.PositiveIntegerField(
                        default=1, help_text="Optimistic concurrency token"
                    ),
                ),
                (
                    "workflow_state",
                    models.CharField(db_index=True, default="draft", max_length=40),
                ),
                (
                    "processing_notes",
                    models.JSONField(
                        default=list,
                        help_text="Operator-safe processing results and questions",
                    ),
                ),
                ("publish_files", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to="submissions.submission",
            ),
        ),
        migrations.CreateModel(
            name="SubmissionRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("record", models.JSONField()),
                (
                    "proposed_records",
                    models.JSONField(
                        default=dict,
                        help_text="{authors|sources|relations: {id: record}} frozen with the revision",
                    ),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=80)),
                (
                    "confirmed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("operation_key", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("publish_files", models.BooleanField(default=False)),
                ("public_metadata_acknowledged", models.BooleanField(default=False)),
                (
                    "admission_decision",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Set only from engine output",
                        max_length=24,
                    ),
                ),
                ("source_file_hashes", models.JSONField(default=list)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "repairs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repaired_by",
                        to="submissions.submissionrevision",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["submission", "number"],
                "unique_together": {("submission", "number")},
            },
        ),
        migrations.CreateModel(
            name="ReviewCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            (
                                "identity_claim",
                                "Claimed ownership of an existing identity",
                            ),
                            (
                                "ambiguous_source",
                                "Ambiguous source or version identity",
                            ),
                            ("edit_ownership", "Conflicting edit ownership"),
                            ("attribution", "Disputed or unverified attribution"),
                            (
                                "unsupported_relation",
                                "Proposed relation lacks stated evidence",
                            ),
                            (
                                "taxonomy_or_governing",
                                "Taxonomy or governing change requested",
                            ),
                            ("publication_exception", "Publication exception"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        help_text="Exact issue and the evidence requested"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("resolved", "resolved"),
                            ("returned_to_researcher", "returned_to_researcher"),
                        ],
                        default="open",
                        max_length=30,
                    ),
                ),
                ("resolution", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_cases",
                        to="submissions.submission",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_cases",
                        to="submissions.submissionrevision",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="submissions.submissionrevision",
            ),
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("storage_key", models.CharField(max_length=300, unique=True)),
                (
                    "filename",
                    models.CharField(
                        help_text="Display metadata only; never a filesystem path",
                        max_length=300,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("byte_count", models.BigIntegerField(default=0)),
                (
                    "sha256",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "client_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("visibility", models.CharField(default="private", max_length=10)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("complete", "complete"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, default="", max_length=300)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Archive this member was extracted from",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="submissions.upload",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploads",
                        to="submissions.submissionrevision",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploads",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FieldEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_path", models.CharField(db_index=True, max_length=120)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("source-extraction", "Extracted from a source file"),
                            ("researcher-statement", "Stated by the researcher"),
                            ("library-classification", "Local library classification"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "value_preview",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "locator",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="page 3 / paragraph 12 / line 40 / record:title",
                        max_length=200,
                    ),
                ),
                (
                    "source_version",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "processing",
                    models.JSONField(
                        default=dict,
                        help_text="parser, version, ocr flag, model service/version if used",
                    ),
                ),
                ("uncertain", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="submissions.submission",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="submissions.submissionrevision",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="submissions.upload",
                    ),
                ),
            ],
            options={
                "ordering": ["field_path", "created_at"],
            },
        ),
    ]
