# Generated by Django 5.2.17 on 2026-09-14 20:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NamespaceLock",
            fields=[
                (
                    "namespace",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("committed_sha", models.CharField(max_length=64, unique=True)),
                ("search_index", models.JSONField()),
                ("profiles", models.JSONField()),
                ("bridge_candidates", models.JSONField()),
                ("object_history", models.JSONField(default=dict)),
                ("receipts", models.JSONField(default=dict)),
                ("taxonomies", models.JSONField(default=dict)),
                ("schema_version", models.CharField(max_length=40)),
                ("taxonomy_version", models.CharField(max_length=40)),
                ("is_current", models.BooleanField(db_index=True, default=False)),
                (
                    "refreshed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_id", models.CharField(max_length=80, unique=True)),
                ("event", models.CharField(max_length=40)),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("summary", models.CharField(blank=True, default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namespace", models.CharField(max_length=8)),
                ("value", models.CharField(max_length=16)),
                ("operation_key", models.CharField(db_index=True, max_length=64)),
                ("purpose", models.CharField(max_length=200)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("local", "local"),
                            ("ledger_queued", "ledger_queued"),
                            ("ledger_committed", "ledger_committed"),
                            ("withdrawn", "withdrawn"),
                        ],
                        default="local",
                        max_length=20,
                    ),
                ),
                (
                    "ledger_path",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "committed_sha",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("namespace", "value"), name="unique_namespace_value"
                    ),
                    models.UniqueConstraint(
                        fields=("namespace", "operation_key"),
                        name="one_value_per_operation_per_namespace",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EvaluationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_key", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("submission_hash", models.CharField(max_length=80)),
                ("engine_revision", models.CharField(max_length=80)),
                ("registry_base", models.CharField(max_length=64)),
                ("schema_version", models.CharField(max_length=40)),
                ("taxonomy_version", models.CharField(max_length=40)),
                ("decision", models.CharField(blank=True, default="", max_length=24)),
                ("gate_results", models.JSONField(default=dict)),
                ("receipt_id", models.CharField(blank=True, default="", max_length=12)),
                ("receipt", models.JSONField(default=dict)),
                ("execution_manifest", models.JSONField(default=dict)),
                (
                    "candidate_validation",
                    models.JSONField(
                        default=list,
                        help_text="Issues from validating the complete candidate registry",
                    ),
                ),
                (
                    "files",
                    models.JSONField(
                        default=dict,
                        help_text="{repo path: content} produced in the candidate checkout",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="submissions.reviewcase",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="submissions.submissionrevision",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="registry_bridge.evaluationattempt",
                    ),
                ),
            ],
            options={
                "ordering": ["recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_key", models.UUIDField(unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("author_registration", "Author registration"),
                            ("admission", "Admission bundle"),
                        ],
                        max_length=30,
                    ),
                ),
                ("summary", models.CharField(max_length=200)),
                (
                    "files",
                    models.JSONField(
                        default=dict,
                        help_text="{repo path: content} — reviewed paths only",
                    ),
                ),
                (
                    "reservations",
                    models.JSONField(
                        default=list,
                        help_text="identifier values whose ledger entries this publication carries",
                    ),
                ),
                (
                    "expected",
                    models.JSONField(
                        default=dict,
                        help_text="what must be verifiable on the default branch afterwards",
                    ),
                ),
                ("base_sha", models.CharField(blank=True, default="", max_length=64)),
                ("branch", models.CharField(blank=True, default="", max_length=120)),
                ("head_sha", models.CharField(blank=True, default="", max_length=64)),
                ("pr_number", models.IntegerField(blank=True, null=True)),
                ("merge_sha", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("branched", "branched"),
                            ("pr_open", "pr_open"),
                            ("checks_pending", "checks_pending"),
                            ("awaiting_review", "awaiting_review"),
                            ("merged", "merged"),
                            ("verified", "verified"),
                            ("blocked", "blocked"),
                            ("abandoned", "abandoned"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "blocker",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Exact required action when blocked",
                    ),
                ),
                ("retries", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publications",
                        to="registry_bridge.evaluationattempt",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="RegistryProjection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(db_index=True, max_length=12)),
                ("record_id", models.CharField(db_index=True, max_length=24)),
                ("committed_sha", models.CharField(db_index=True, max_length=64)),
                ("payload", models.JSONField()),
                ("payload_hash", models.CharField(max_length=80)),
                (
                    "refreshed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "unique_together": {("kind", "record_id", "committed_sha")},
            },
        ),
    ]
